on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: install dependencies
        run: npm install
      - name: build production app
        run: npm run build
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
