on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
      - name: build production app
        run: npm build
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout/@v4
      - name: Deploy to production
        run: echo deploying to production
